name: CD

on:
  workflow_dispatch:

jobs:
  cd_chromium_firefox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch Dependencies
        run: |
          sudo apt install -y jq make zip imagemagick npm
          npm install --global web-ext purgecss

      - name: Build & Sign Firefox Extension
        shell: bash
        env:
          FIREFOX_API_KEY: ${{ secrets.FIREFOX_API_KEY }}
          FIREFOX_API_SECRET: ${{ secrets.FIREFOX_API_SECRET }}
        run: |
          echo "$FIREFOX_API_KEY" > keys/firefox_api_key.key
          echo "$FIREFOX_API_SECRET" > keys/firefox_api_secret.key
          make firefox_publish

      - name: Upload Firefox ZIP Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: CD-ZIP-Firefox
          path: build/zip/Firefox.zip
      
      - name: Upload Firefox XPI Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: CD-XPI-Firefox
          path: build/dist/Firefox.xpi
      
      - run: |
          echo "RL_VERSION_N=$(cat manifests/v3.json | jq -r '.version')" >> $GITHUB_ENV
      - run: |
          echo "RL_VERSION_TITLE=$(echo \"Release v${{ env.RL_VERSION_N }}\")" >> $GITHUB_ENV

      - name: Create A Release On Github
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.RL_VERSION_N }}"
          prerelease: false
          title: "${{ env.RL_VERSION_TITLE }}"
          files: |
            ./build/dist/Chromium.zip
            ./build/dist/Firefox.xpi