name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  ci_chromium_firefox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch Dependencies
        run: |
          sudo apt install -y python3 python3-pip npm
          npm install --global purgecss
          pip install Pillow tqdm
      
      - name: Build
        run: |
          python build.py

      - name: Upload Chromium Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: CI-ZIP-Chromium
          path: build/Chromium.zip

      - name: Upload Firefox Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: CI-ZIP-Firefox
          path: build/Firefox.zip