name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  ci_chromium_firefox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch Dependencies
        run: |
          sudo apt install -y make zip imagemagick npm
          npm install --global purgecss

      - name: Build Chrome & Firefox
        run: make chromium firefox

      - name: Upload Chromium Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: CI-ZIP-Chromium
          path: build/zip/Chromium.zip

      - name: Upload Firefox Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: CI-ZIP-Firefox
          path: build/zip/Firefox.zip